### ISSUE TITLE
z-index issue on iOS devices

### ISSUE THREAD

**Issue by hschaefer123** [shhdharmen/keyboard-css#9]
**Describe the bug**
Using the library inside VitePress, the buttons will be wrongly shown above the menu on scrolling.

**Expected behavior**
The library should not change the z-index for the buttons.

**Screenshot**
![thumbnail_IMG_0133](https://github.com/shhdharmen/keyboard-css/assets/2110971/7bb53f1d-ab9a-4f71-8d50-3a4756c14fb4)

**iOS Device:**
This seems to be an iOS device issue, where doing a 3d/z transform wrongly changes the z-index!

**Fix**
Inside _button.scss add 
```transform: translate3d(0,0,0); // fix z-index issue```
after
```transform: translate3d(0, 0, #{$kbc-btn-depth}px); ```
to reset the z layer issue.

Hint: SASS is also translating the above translate3d(0,0,x) into translatez(x) eliminating the zeros.

Regards
Holger

**Comment by shhdharmen** [comment]
Which browser you're using? Did you check in all browsers?

**Comment by hschaefer123** [comment]
This seems to be only a known issue on Apple iOS devices like iPad/iPhone.

The screenshot is from my iPad Pro.

While googling for the issue and a solution, i came across the fix. Other fixes like using transform-style:  flat does not work for me.

**Comment by shhdharmen** [comment]
But which browser you're using? Did you check in all browsers?

**Comment by hschaefer123** [comment]
For me, it is now working correct in 
- Chrome Win/Mac. 
- MS Edge
- iOS iPad and iPhone

See live example with the fix
[BTP reveal site with used keys](https://btp.udina.de/development/reveal.html)

I do not see any visual differences.

BR
Holger
